#%RAML 1.0 Trait
queryParameters:
  fromDate?:
    type: date-only
    description: The start for the search. Inclusive.
  toDate?:
    type: date-only
    description: The end date for the search. Inclusive.
    