#%RAML 1.0 Library
usage: Contains all traits used for ADT Common Artifacts RAMl sepcification
traits:
  clientIdRequired: !include clientIdRequired.raml
  securedWithBasic: !include securedWithBasic.raml
  historicSearch: !include historicSearch.raml
  pagable: !include pagable.raml
  correlationIdRequired: !include correlationIdRequired.raml
  applicationIdRequired: !include applicationIdRequired.raml
  standardSystemAPIHeaders: !include standardSystemAPIHeaders.raml
  standardAPIHeaders: !include standardAPIHeaders.raml