#%RAML 1.0 NamedExample
value:  
  statusCode: "A"
  declinedTransactionFound: false
  isUnenrolled: false
  enrollmentDate: "2020-11-17"
  recurringPaymentTypeCode: "ACH"
  creditCardTypeCode: "A"
  creditCardNumber: "3036"
  creditCardExpirationDate: "2024-07-31"
  bankAccountNumber: "*******2365"
  bankRoutingNumber: "091000022"
  bankAccountType: null
  invoiceMasterId: 10150920
  prepayId: 36125332
  withdrawDay: 0
  billCycleId: "12"
  dayOfMonth: 20
  draftDayChangeAllowed: false
  draftDayUpdateMessage: "Easy pay message"