#%RAML 1.0 NamedExample
value:  
  referenceId: 184265194
  effectiveDate: "2020-11-17"
  accountNumberLast4Digits: "9424"
  amount: 50.45
  paymentTypeCode: null
  paymentType: "Discover"
  isCancellable: null
  isCancelled: false