#%RAML 1.0 DataType
properties:
  accountId:
    type: integer
    description: customer account id
  billingSystemCode:
    type: string
    description:  billing system code
  statusCode?:
    type: string | nil
    description: 
  dealTypeCode?:
    type: string | nil
    description: 
  masterSubAccountCode?:
    type: string | nil
    description: 
  flexFinanceCode?:
    type: string | nil
    description: 
  creditFraudFlag?:
    type: string | nil
    description: 