#%RAML 1.0 DataType
type: string
enum: ["1", "2","3","4","5","6","13","14","15","16","17","18","19","21"]
description:  |
  1=Customer Test - 1 hour
  2=Service/Repair - 2 hours
  3=Install/Svc - 8 hours
  4=Inspection
  5=ASI/Guard
  6=Temp out of service
  13=2-Way Voice
  14=Service/Repair - 10 hours
  15=Service/Repair - 4 hours
  16=Customer Test-VRT
  17=5 day Familiarization
  18=7 day Familiarization
  19=14 day Fam/Cut-In
  21=AHJ On Scene