#%RAML 1.0 DataType
type: object
properties:
  alternateItemId?:
    type: string | nil
  bundleFulfillmentMode?:
    type: string
    maxLength: 2
  costCurrency?:
    type: string | nil
  countryOfOrigin?:
    type: string | nil
  customerItem?:
    type: string | nil
  customerItemDescription?:
    type: string | nil
  eccnNumber?:
    description: The Export Commodity Control Number
    type: string | nil
  harmonizedCode?:
    type: string | nil
  isbn?:
    type: string | nil
  itemDescription?:
    type: string | nil
  itemId?:
    type: string | nil
  itemShortDescription?:
    type: string | nil
  itemWeight?:
    type: string | nil
  itemWeightUom?:
    type: string | nil
  manufacturerItem?:
    type: string | nil
  manufacturerItemDescription?:
    type: string | nil
  manufacturerName?:
    type: string | nil
  nmfcClass?:
    description: The class of the National Motor Freight Classification
    type: string | nil
  nmfcCode?:
    description: The code of the National Motor Freight Classification
    type: string | nil
  nmfcDescription?:
    description: The description of the National Motor Freight Classification
    type: string | nil
  productClass?:
    type: string | nil
  productLine?:
    type: string | nil
  scheduleBCode?:
    type: string | nil
  supplierItem?:
    type: string | nil
  supplierItemDescription?:
    type: string | nil
  taxProductCode?:
    type: string | nil
  upcCode?:
    type: string | nil
  unitCost?:
    type: string | nil
  unitOfMeasure?:
    type: string | nil
  languageDescriptionList?:
    type: string | nil
