#%RAML 1.0 NamedExample
request-example1:
  {
    "documentNumber": "889735106",
    "documentDate": "2021-03-02T18:00:00-06:00",
    "transactionType": "SALE",
    "seller": {
      "company": "601",
      "physicalOrigin": {
        "streetAddress1": "14500 TRINITY BLVD",
        "streetAddress2": "SUITE 114",
        "city": "FORT WORTH",
        "mainDivision": "TX",
        "subDivision": "TARRANT",
        "postalCode": "761552528",
        "country": "USA"
      },
      "administrativeOrigin": {
        "city": "FORT WORTH",
        "mainDivision": "TX",
        "postalCode": "761552528"
      }
    },
    "customer": {
      "destination": {
        "streetAddress1": "63 S. Illinois Lane",
        "streetAddress2": "",
        "city": "AMARILLO",
        "mainDivision": "TX",
        "subDivision": "POTTER",
        "postalCode": "79106"
      }
    },
    "lineItems": [
      {
        "lineItemNumber": "1",
        "usageClass": "Fire Alarm",
        "extendedPrice": "126418.42",
        "productClass": "OFFSITE LABOR",
        "quantity": "1",
        "product": {
          "productCode": "OFFSITE LABOR"
        },
        "flexibleFields": {
          "flexibleCodeField": [
            {
              "fieldId": "1",
              "value": "N"
            },
            {
              "fieldId": "3",
              "value": "Sales Pilot"
            },
            {
              "fieldId": "6",
              "value": "Y"
            },
            {
              "fieldId": "10",
              "value": "Testing"
            },
            {
              "fieldId": "16",
              "value": "889735106"
            },
            {
              "fieldId": "17",
              "value": "Yes"
            },
            {
              "fieldId": "20",
              "value": "New Construction"
            },
            {
              "fieldId": "21",
              "value": "66634"
            }
          ]
        }
      },
      {
        "lineItemNumber": "2",
        "usageClass": "Fire Alarm",
        "extendedPrice": "126418.42",
        "productClass": "OFFSITE LABOR",
        "quantity": "1",
        "product": {
          "productCode": "OFFSITE LABOR"
        },
        "flexibleFields": {
          "flexibleCodeField": [
            {
              "fieldId": "1",
              "value": "N"
            },
            {
              "fieldId": "3",
              "value": "Sales Pilot"
            },
            {
              "fieldId": "6",
              "value": "Y"
            },
            {
              "fieldId": "10",
              "value": "Testing"
            },
            {
              "fieldId": "16",
              "value": "889735106"
            },
            {
              "fieldId": "17",
              "value": "Yes"
            },
            {
              "fieldId": "20",
              "value": "New Construction"
            },
            {
              "fieldId": "21",
              "value": "66634"
            }
          ]
        }
      }
    ]
  }