#%RAML 1.0 DataType
example: 
properties:
  customerId?:
    type: integer
    format: int32
  firstName?:
    type: string
  lastName?:
    type: string
  address?:
    type: !include ../address.raml   
  phoneNumber?:
    type: string
  