#%RAML 1.0 NamedExample
value:
    score: "714"
    modelName: "EQUIFAX_02525"
    reasons:
    -
      code: "00041"
      description: "Percent of Bank Revolving Accounts versus Total Accounts Reported in the Past 12 Months"
    -
      code: "00028"
      description: "Too Few Bank Revolving Accounts Currently or in the Past Paid as Agreed"
    -
      code: "00027"
      description: "Too Few Accounts Currently or in the Past Paid as Agreed"
    -
      code: "00043"
      description: "Percent of Bank Installment Accounts versus Total Accounts Reported in the Past 12 Month"