#%RAML 1.0 DataType
displayName: CurrencyType
description: |
  The monetary unit to be used in calculations as defined by ISO 4217 standard.
type: object
properties:
  isoCurrencyName:
    required: false
    displayName: isoCurrencyName
    description: The ISO 4217 name for the currency unit. Not used for this version of O Series.
    type: string
  isoCurrencyCodeAlpha:
    required: false
    displayName: isoCurrencyCodeAlpha
    description: The three-character ISO 4217 alphabetic code for the currency unit.
    type: string
    pattern: '[A-Z]{3}'
  isoCurrencyCodeNum:
    required: false
    displayName: isoCurrencyCodeNum
    description: The three-digit ISO 4217 numeric code for the currency unit.
    type: integer
    minimum: 1
    maximum: 999
    format: int32