#%RAML 1.0 DataType
displayName: CurrencyConversionFactorType
type: object
properties:
  sourceCurrency:
    required: true
    displayName: SourceCurrency
    description: The currency in which the transaction amount is passed for calculation.
    type: Currency
  targetCurrency:
    required: true
    displayName: TargetCurrency
    description: The tax rule currency to which the transaction amount will be converted for calculation.
    type: Currency
  conversionFactor:
    required: true
    displayName: ConversionFactor
    description: The conversion multiplier for converting a source currency to a target currency.
    type: number
    format: double