#%RAML 1.0 DataType
displayName: PhysicalLocation
description: The physical location associated with the tax registration. Use the taxAreaId or address information to identify the physical location.
type: object    
properties:
  taxAreaId:
    required: false
    displayName: TaxAreaId
    description: Tax Area ID for the location.
    type: integer
    minimum: 0
    maximum: 999999999
    format: int32
  streetAddress1:
    required: false
    displayName: StreetAddress1
    description: The first line of the street address.
    type: string
    minLength: 1
    maxLength: 100
  streetAddress2:
    required: false
    displayName: StreetAddress2
    description: The second address line for a Contact.
    type: string
    minLength: 1
    maxLength: 100
  city:
    required: false
    displayName: City
    description: The proper name of the city used to determine the Tax Area ID (if none is supplied). Optional (0..1) but recommended for greatest accuracy if no Tax Area ID is supplied.
    type: string
    minLength: 1
    maxLength: 60
  mainDivision:
    required: false
    displayName: MainDivision
    description: The proper name or the postal abbreviation of the state, province, or territory used to determine the Tax Area ID if none is supplied. Optional (0..1) but is recommended for greatest accuracy if no Tax Area ID is supplied.
    type: string
    minLength: 1
    maxLength: 60
  subDivision:
    required: false
    displayName: SubDivision
    description: The name of the county used to determine the Tax Area ID if none is supplied. Optional (0..1) but is recommended for greatest accuracy if no Tax Area ID is supplied.
    type: string
    minLength: 1
    maxLength: 60
  postalCode:
    required: false
    displayName: PostalCode
    description: The postal code used to determine the Tax Area ID (if none is supplied).
    type: string
    minLength: 1
    maxLength: 20
  country:
    required: false
    displayName: Country
    description: The country used to determine the Tax Area ID (if none is supplied). You can use a Data Extract report to see the valid country values.)
    type: string
    minLength: 1
    maxLength: 60