#%RAML 1.0 DataType
displayName: TaxTransactionRequestType

description: Request Type for Quotation/Invoice Taxes. The request used to estimate taxes on the proposed sale, rental, or lease of goods or services by the Seller.

properties:
  applicationData:
    required: false
    displayName: applicationData
    type: object
    properties:
      sender:
        required: false
        displayName: sender
        type: string
  documentNumber:
    required: false
    displayName: documentNumber
    description: The document number in the host application that references the event.
    type: string
    minLength: 1
    maxLength: 50
  accumulationDocumentNumber:
    required: false
    displayName: accumulationDocumentNumber
    description: A string to represent the accumulation invoice identity.
    type: string
    minLength: 1
    maxLength: 40
  accumulationCustomerNumber:
    required: false
    displayName: accumulationCustomerNumber
    description: A string to represent the accumulation customer identity.
    type: string
    minLength: 1
    maxLength: 40
  documentType:
    required: false
    displayName: documentType
    description: Indicates the type of business transaction to be posted. This field is on the transaction level.
    type: string
    minLength: 1
    maxLength: 20
  billingType:
    required: false
    displayName: billingType
    description: Indicates the billing documents that specify different business transactions that are involved in billing activities. Examples of billing documents include  invoice, credit or debit memo, or cancellation document. This field is on the transaction level.
    type: string
    minLength: 1
    maxLength: 20
  orderType:
    required: false
    displayName: orderType
    description: The key that identifies the purpose of the order. This field is on the transaction level.
    type: string
    minLength: 1
    maxLength: 20
  postingDate:
    required: false
    displayName: postingDate
    description: The date when the transaction is posted for auditing and reporting purposes. If no date is provided, the Calculation Engine uses the date when the transaction was processed.
    type: date-only
  locationCode:
    required: false
    displayName: locationCode
    description: A value that can be used for tax return filing in jurisdictions that require taxes to be filed for individual retail locations.
    type: string
    minLength: 1
    maxLength: 20
  returnAssistedParametersIndicator:
    required: false
    displayName: returnAssistedParametersIndicator
    description: Indicates whether the response message should contain an additional structure that shows the elements/attributes that were changed by Tax Assist. This is for informational purposes only and contains no tax results.
    type: boolean
  returnGeneratedLineItemsIndicator:
    required: false
    displayName: returnGeneratedLineItemsIndicator
    description: If this indicator is set, the response message returns child line items that were generated by the Tax Assist allocation feature. Otherwise, these line items are deleted after the transaction is written to the Tax Journal and only the primary line item, which contains the combined tax results of the child line items, is passed back to the host system.
    type: boolean
  deliveryTerm:
    required: false
    displayName: deliveryTerm
    description: An identifier that determines the vendor or customer jurisdiction in which the title transfer of a supply takes place. This is also known as Shipping Terms. Delivery Terms information could be critical to determine the place of supply, for example, in distance selling.
    type: string
    enum:
    - EXW
    - FCA
    - FAS
    - FOB
    - CFR
    - CIF
    - CPT
    - CIP
    - DAF
    - DES
    - DEQ
    - DDU
    - DDP
    - DAP
    - DAT
    - SUP
    - CUS
  documentDate:
    required: true
    displayName: documentDate
    description: The actual date of the requested action. The calculation engine uses this date to determine the valid tax rates and rules.
    type: date-only
  transactionId:
    required: false
    displayName: transactionId
    description: An identifier that further defines the document and corresponds to the transaction stored in the host system. The Transaction ID is used for synchronization services, but is not used for reporting purposes.
    type: string
    minLength: 1
    maxLength: 40
  transactionType:
    required: true
    displayName: transactionType
    description: An identifier for the specific transaction type to be used by the transaction and/or line item. If transactionType is not set at the line item level, the line item uses the transaction level value.
    type: string
    enum:
    - SALE
    - RENTAL
    - LEASE
  simplificationCode:
    required: false
    displayName: simplificationCode
    description: A code that indicates a special action on the transaction being processed.
    type: string
    enum:
    - CONSIGNMENT
    - CALL_OFF
    - TRIANGULATION
    - REGISTRATION_GROUP
  roundAtLineLevel:
    required: false
    displayName: roundAtLineLevel
    description: |
      The roundAtLineLevel attribute enables you to apply line-item level or invoice-level rounding to tax calculations. 
    type: boolean
  paymentDate:
    required: false
    displayName: paymentDate
    description: The date the purchaser paid for the product. If the purchaser pays for the product but physically receives it at a later date, this field is used for returns and reporting for your tax type.  This field is also used in cash accounting.
    type: date-only
  documentSequenceId:
    required: false
    displayName: documentSequenceId
    description: Use this field for audit purposes to track the sequence of your documents.
    type: string
    minLength: 0
    maxLength: 60
  taxPointDate:
    required: false
    displayName: taxPointDate
    description: The date that drives the timing of when the VAT liability arises. In some countries, if the Tax Point Date, (also called the Time of Supply) is different from the invoice date, this field is shown separately on an invoice. Use this field if you have reporting compliance in Spain, Poland, and Hungary.
    type: date-only
  currency:
    required: false
    displayName: Currency
    description: Default unit of currency for the entire transaction.
    type: Currency   
  originalCurrency:
    required: false
    displayName: OriginalCurrency
    description: This represents the currency in which the original business transaction took place.
    type: Currency
  companyCodeCurrency:
    required: false
    displayName: CompanyCodeCurrency
    description: |
      The default currency code of the company that is integrated with the ERP or host system.
    type: Currency
  seller:
    required: false
    displayName: Seller
    description: The seller for the transaction. The seller is described by the child elements and attributes.
    type: Seller
  customer:
    required: false
    displayName: Customer
    description: The customer for the transaction. The customer is described by the child elements and attributes.
    type: Customer
  taxOverride:
    required: false
    displayName: TaxOverride
    description: Details on the tax override.
    type: TaxOverride
  impositionToProcess:
    required: false
    displayName: ImpositionToProcess
    description: |
      Limits the taxes calculated for the transaction to a specific jurisdiction level and imposition type.
    type: array
    items:
      type: ImpositionToProcess
  jurisdictionOverride:
    required: false
    displayName: JurisdictionOverride
    description: Details on the jurisdiction overrides.
    type: array
    items:
      type: JurisdictionOverride
  situsOverride:
    required: false
    displayName: SitusOverride
    description: Details on the situs determination overrides.
    type: object
    properties:
      taxingLocation:
        required: true
        displayName: taxingLocation
        description: |
          The address type to be used as the situs. Required if performing a situs override.
        type: string
        enum:
        - ADMINISTRATIVE_DESTINATION
        - ADMINISTRATIVE_ORIGIN
        - DESTINATION
        - PHYSICAL_ORIGIN
  discount:
    required: false
    displayName: Discount
    description: |
      Details on the discount. To pass Discount information, pass either DiscountPercent or DiscountAmount, but not both.
    type: object
    properties:
      userDefinedDiscountCode:
        required: false
        displayName: A user-defined code that maps to discount category.
        type: string
      amount:
        required: false
        displayName: DiscountAmount
        description: The discount to be applied expressed as an amount.
        type: number
        format: double
      percent:
        required: false
        displayName: DiscountPercent
        description: The discount to be applied expressed as a percentage.
        type: number
        minimum: 0
        maximum: 1
        format: double
  proratePercentage:
    required: false
    displayName: ProratePercentage
    description: Percentage passed from the billing system to calculate a remainder of an assessed tax or fee.
    type: number
    minimum: -100000000
    maximum: 100000000
    format: double
  currencyConversionFactors:
    required: false
    displayName: CurrencyConversionFactors
    description: A list of currency conversion factors.
    type: CurrencyConversionFactor[]
  lineItems:
    required: true
    displayName: LineItem
    description: The header for a component of a transaction.  A line item is required for each component of the transaction. Each transaction requires at least one line item. Note that a line item can contain child line items.
    type: array
    items:
      type: LineItemQSI