#%RAML 1.0 DataType
displayName: TaxesType
description: Taxes calculated by the transaction processing system.
type: object
properties:
  taxResult:
    required: false
    displayName: taxResult
    description: |
      System determination of taxable status based on situs and item type.
    
      Note: Tax amounts with a value of Deferred are payable at a later time and should NOT be written to the invoice.
    type: string
    enum:
    - TAXABLE
    - NONTAXABLE
    - EXEMPT
    - DPPAPPLIED
    - NO_TAX
    - DEFERRED
  taxType:
    required: false
    displayName: taxType
    description: System determined tax type, based on situs, transaction type, and party role type (perspective).
    type: string
    enum:
    - SALES
    - SELLER_USE
    - CONSUMERS_USE
    - VAT
    - IMPORT_VAT
    - NONE
  maxTaxIndicator:
    required: false
    displayName: maxTaxIndicator
    description: Indicates that max tax was applied to this line item of the invoice.
    type: boolean
  situs:
    required: false
    displayName: situs
    description: The situs determined by the calculation engine for the line item.
    type: string
    enum:
    - ADMINISTRATIVE_DESTINATION
    - ADMINISTRATIVE_ORIGIN
    - DESTINATION
    - PHYSICAL_ORIGIN
  notRegisteredIndicator:
    required: false
    displayName: notRegisteredIndicator
    description: Indicates that the taxpayer company is not registered in the taxing jurisdiction.
    type: boolean
  inputOutputType:
    required: false
    displayName: inputOutputType
    description: Identifies whether tax is Input VAT, Output VAT, or both according to the perspective of the transaction to allow for Reverse Charges.
    type: string
    enum:
    - INPUT
    - IMPORT
    - OUTPUT
    - INPUT_OUTPUT
  taxCode:
    required: false
    displayName: taxCode
    description: A user-defined code for the tax, to be returned to your host system after tax calculation. To return a value for this field, set up a post-calculation Tax Assist rule.
    type: string
  vertexTaxCode:
    required: false
    displayName: vertexTaxCode
    description: A code that can be used to classify the transaction at the tax level for reporting or tax return filing purposes. The code is generated by the Calculation Engine for each line item after tax calculation. It can be used as a filter for reports or as an input for post-calculation Tax Assist rules.
    type: string
  reasonCode:
    required: false
    displayName: reasonCode
    description: |
      A code that indicates the reason for the exception that was applied to this tax.
      
      Note: For a tax with multiple tiers, API returns the reason code associated with the largest basis amount.

      Note: To pass a standard (i.e., not user-defined) single-digit reason code, pad the code to four digits.
    type: string
    minLength: 1
    maxLength: 4
  filingCategoryCode:
    required: false
    displayName: filingCategoryCode
    description: Provides additional classification of the transaction for tax returns and reporting. Codes are jurisdiction-specific.
    type: integer
    minimum: 1
    maximum: 99999
    format: int32
  isService:
    required: false
    displayName: isService
    description: Indicates whether or not the product is a service.
    type: boolean
  rateClassification:
    required: false
    displayName: rateClassification
    description: |
      A Vertex-defined classification of the applicable tax rule for returns filing purposes. Possible values are: Luxury Rate, Standard Rate, Reduced Rate 1, Reduced Rate 2, Reduced Rate 3, Reduced Rate 4, Reduced Rate 5, User Defined, Zero Rate, Outside the Scope.
    type: string
  taxCollectedFromParty:
    required: false
    displayName: taxCollectedFromParty
    description: |
      The party who is responsible for the sales tax.
    
      Note: Tax amounts with a value of Seller cannot be charged to your customer and should NOT be written to the invoice.
    type: string
    enum:
    - SELLER
    - BUYER
  taxStructure:
    required: false
    displayName: taxStructure
    description: Specifies the applicable tax structure when the transaction includes a flat fee or quantity-based fee.
    type: string
    enum:
    - BRACKET
    - FLAT_TAX
    - QUANTITY
    - SINGLE_RATE
    - TIERED
    - QUANTITY_TIERED
    - QUANTITY_RATE_TIERED
    - TIERED_MODIFIER
    - QUANTITY_TIERED_MODIFIER
    - QUANTITY_RATE_TIERED_MODIFIER
    - QUANTITY_TIERED_FLAT
    - TIERED_FLAT
    - QUANTITY_RATE_TIERED_EQUIVALENT
  jurisdiction:
    required: false
    displayName: Jurisdiction
    description: The name of jurisdiction to which a tax is applied.
    type: object
    properties:
        jurisdictionName:
            required: false
            displayName: externalJurisdictionCode
            description: "The name that this jurisdiction is commonly known. For example, Pennsylvania."
            type: string
            minLength: 0
            maxLength: 20
        jurisdictionLevel:
            required: true
            displayName: jurisdictionLevel
            description: |
                The level of the jurisdiction for which the tax on the line item is applied.
            type: string
            enum:
            - APO
            - BOROUGH
            - CITY
            - COUNTRY
            - COUNTY
            - DISTRICT
            - FPO
            - LOCAL_IMPROVEMENT_DISTRICT
            - PARISH
            - PROVINCE
            - SPECIAL_PURPOSE_DISTRICT
            - STATE
            - TERRITORY
            - TOWNSHIP
            - TRADE_BLOCK
            - TRANSIT_DISTRICT
        jurisdictionId:
            required: true
            displayName: jurisdictionId
            type: integer
            minimum: 0
            maximum: 999999999
            format: int32
        effectiveDate:
            required: false
            displayName: effectiveDate
            description: The date when the tax for the jurisdiction became effective.
            type: date-only
        expirationDate:
            required: false
            displayName: expirationDate
            description: The date after which the tax for the jurisdiction is no longer effective.
            type: date-only
        externalJurisdictionCode:
            required: false
            displayName: externalJurisdictionCode
            description: Jurisdiction code assigned by the relevant governmental authority.
            type: string
            minLength: 0
            maxLength: 20
  accumulateAsJurisdiction:
    required: false
    displayName: AccumulateAsJurisdiction
    description: The name of jurisdiction to which the tax is accumulated to.
    type: object
    properties:
        jurisdictionName:
            required: false
            displayName: externalJurisdictionCode
            description: "The name that this jurisdiction is commonly known. For example, Pennsylvania."
            type: string
            minLength: 0
            maxLength: 20
        jurisdictionLevel:
            required: true
            displayName: jurisdictionLevel
            description: |
                The level of the jurisdiction for which the tax on the line item is applied.
            type: string
            enum:
            - APO
            - BOROUGH
            - CITY
            - COUNTRY
            - COUNTY
            - DISTRICT
            - FPO
            - LOCAL_IMPROVEMENT_DISTRICT
            - PARISH
            - PROVINCE
            - SPECIAL_PURPOSE_DISTRICT
            - STATE
            - TERRITORY
            - TOWNSHIP
            - TRADE_BLOCK
            - TRANSIT_DISTRICT
        jurisdictionId:
            required: true
            displayName: jurisdictionId
            type: integer
            minimum: 0
            maximum: 999999999
            format: int32
        effectiveDate:
            required: false
            displayName: effectiveDate
            description: The date when the tax for the jurisdiction became effective.
            type: date-only
        expirationDate:
            required: false
            displayName: expirationDate
            description: The date after which the tax for the jurisdiction is no longer effective.
            type: date-only
        externalJurisdictionCode:
            required: false
            displayName: externalJurisdictionCode
            description: Jurisdiction code assigned by the relevant governmental authority.
            type: string
            minLength: 0
            maxLength: 20
  calculatedTax:
    required: false
    displayName: CalculatedTax
    description: Amount of tax calculated by the calculation engine.
    type: number
    format: double
  effectiveRate:
    required: false
    displayName: EffectiveRate
    description: For Buyer Input tax and Seller Import tax, this rate is calculated based on the Extended Price and Tax Amount (Import or Input) passed in the Request message. If you total the Extended Price and Tax Amounts before passing them in, this rate is an average. For all other message types, this is the effective rate the system used to calculate tax.
    type: number
    minimum: 0
    format: double
  taxApportionmentRate:
    required: false
    displayName: TaxApportionmentRate
    description: The tax apportionment rate to apportion the calculated tax between two different locaitons.
    type: number
    minimum: 0
    format: double
  basisReductionPercentage:
    required: false
    displayName: BasisReductionPercentage
    description: the percentage by which a basis amount is reduced in a tax calculation.
    type: number
    minimum: 0
    format: double
  exempt:
    required: false
    displayName: Exempt
    description: Amount or count of the line item not subject to tax due to exempt status.
    type: number
    format: double
  exemptUnitOfMeasure:
    required: false
    displayName: ExemptUnitOfMeasure
    description: The unit of measure for the line item to be used in surcharges based on quantity and not price.
    type: string
  nonTaxable:
    required: false
    displayName: NonTaxable
    description: Amount or count of the line item not subject to tax due to nontaxable status.
    type: number
    format: double
  nonTaxableUnitOfMeasure:
    required: false
    displayName: NonTaxableUnitOfMeasure
    description: The unit of measure for the line item to be used in surcharges based on quantity and not price.
    type: string
  taxable:
    required: false
    displayName: Taxable
    description: Amount or count of the line item subject to tax.
    type: number
    format: double
  taxableUnitOfMeasure:
    required: false
    displayName: TaxableUnitOfMeasure
    description: The unit of measure for the line item to be used in surcharges based on quantity and not price.
    type: string
  reportingBasis:
    required: false
    displayName: ReportingBasis
    description: Amount subject to reporting basis.
    type: number
    format: double
  imposition:
    required: false
    displayName: Imposition
    description: The name of the imposition to which the relevant tax rule belongs.
    properties:
      name:
        required: false
        displayName: Name
        description: The name of the imposition to which the relevant tax rule belongs.
        type: string
      userDefined:
        required: false
        displayName: userDefined
        description: |
          An identifier for user-defined imposition. This identifier is useful for troubleshooting.
        type: boolean
      impositionId:
        required: false
        displayName: impositionId
        description: An identifier for the Imposition.
        type: integer
        format: int32
  impositionType:
    required: false
    displayName: ImpositionType
    description: The type description that is assigned to the imposition.
    properties:
      typeDescription:
        required: false
        displayName: typeDescription
        description: The type description that is assigned to the imposition.
        type: string
      userDefined:
        required: false
        displayName: userDefined
        description: |
          An identifier for user-defined imposition type. This identifier is useful for troubleshooting.
        type: boolean
      impositionTypeId:
        required: false
        displayName: impositionTypeId
        description: An identifier for the impositionType.
        type: integer
        format: int32
      withholdingType:
        required: false
        displayName: withholdingType
        description: withholding type of the impositionType.
        type: string
  accumulateAsImposition:
    required: false
    displayName: AccumulateAsImposition
    description: The name of the imposition to which the relevant tax rule belongs.
    properties:
      name:
        required: false
        displayName: Name
        description: The name of the imposition to which the relevant tax rule belongs.
        type: string
      userDefined:
        required: false
        displayName: userDefined
        description: |
          An identifier for user-defined imposition. This identifier is useful for troubleshooting.
        type: boolean
      impositionId:
        required: false
        displayName: impositionId
        description: An identifier for the Imposition.
        type: integer
        format: int32
  accumulateAsImpositionType:
    required: false
    displayName: AccumulateAsImpositionType
    description: The type description that is assigned to the accumulate as imposition.
    properties:
      typeDescription:
        required: false
        displayName: typeDescription
        description: The type description that is assigned to the imposition.
        type: string
      userDefined:
        required: false
        displayName: userDefined
        description: |
          An identifier for user-defined imposition type. This identifier is useful for troubleshooting.
        type: boolean
      impositionTypeId:
        required: false
        displayName: impositionTypeId
        description: An identifier for the impositionType.
        type: integer
        format: int32
      withholdingType:
        required: false
        displayName: withholdingType
        description: withholding type of the impositionType.
        type: string
  taxRuleId:
    required: false
    displayName: TaxRuleId
    description: An identifier for the tax rule that was used in tax calculation. This can be used as a troubleshooting aid.
    type: Rule
  basisRuleId:
    required: false
    displayName: BasisRuleId
    description: An identifier for the basis rule that was used in tax calculation. This can be used as a troubleshooting aid.
    type: Rule
  inclusionRuleId:
    required: false
    displayName: InclusionRuleId
    description: An identifier for an inclusion rule.
    type: Rule
  maxTaxRuleId:
    required: false
    displayName: MaxTaxRuleId
    description: An identifier for the Max Tax rule that was used in tax calculation. This can be used as a troubleshooting aid.
    type: Rule
  recoverableRuleId:
    required: false
    displayName: RecoverableRuleId
    description: The identifier of the applicable VAT Recoverability Rule for the line item. This Recoverability Rule determines the percentage of input VAT that is deemed to be unrecoverable. This is an optional child element of the Taxes element.
    type: Rule
  postCalculationEvaluationRuleId:
    required: false
    displayName: PostCalculationEvaluationRuleId
    description: An identifier for the post calculation evaluation rule.
    type: Rule
  creditRuleId:
    required: false
    displayName: CreditRuleId
    description: An identifier for the credit rule.
    type: Rule
  basisApportionmentRuleId:
    required: false
    displayName: BasisApportionmentRuleId
    description: An identifier for a Basis Apportionment Rule. Apportionment rules are specific to each taxpayer. Use this field to identify a user-defined rule that specifies apportionment rates for each taxpayer.
    type: Rule
  taxRateAdjustmentRuleId:
    required: false
    displayName: TaxRateAdjustmentRuleId
    description: An identifier for the tax rate adjustment rule.
    type: Rule
  taxApportionmentRuleId:
    required: false
    displayName: TaxApportionmentRuleId
    description: An identifier for the tax apportionment rule.
    type: Rule
  accumulationRuleId:
    required: false
    displayName: AccumulationRuleId
    description: An identifier for the accumulate rule.
    type: Rule
  telecomUnitConversionRuleId:
    required: false
    displayName: TelecomUnitConversionRuleId
    description: An identifier for the telecommunication unit conversion rule.
    type: Rule
  reportingBasisRuleId:
    required: false
    displayName: ReportingBasisRuleId
    description: An identifier for the reporting basis rule.
    type: Rule
  certificate:
    required: false
    displayName: Certificate
    description: The certificate number associated with the line item tax.
    properties:
      certificateNumber:
        required: false
        displayName: CertificateNumber
        description: The certificate number associated with the line item tax.
        type: string
      certificateType:
        required: false
        displayName: certificateType
        description: The certificate type associated with the line item tax.
        type: string
  recoverableAmount:
    required: false
    displayName: RecoverableAmount
    description: The amount of input or import tax that the buyer is able to recover on a transaction. This is the amount that the Buyer puts on their returns in order to recover these funds.
    type: number
    format: double
  recoverablePercent:
    required: false
    displayName: RecoverablePercent
    description: |
      The percent of the tax that is recoverable, as calculated based on passed in recoverable amount and tax. Expressed as a decimal: 1.0 for 100%, .8 for 80%, .5 for 50%, and so on.
    type: number
    minimum: 0
    maximum: 1
    format: double
  blockingRecoverablePercent:
    required: false
    displayName: BlockingRecoverablePercent
    description: The recoverable override percentage of the blocking override on the Input Tax level.
    type: number
    minimum: 0
    maximum: 1
    format: double
  partialExemptRecoverablePercent:
    required: false
    displayName: PartialExemptRecoverablePercent
    description: The recoverable percentage of a partial exemption. This field is populated only for transactions with a tax type of Value Added Tax.
    type: number
    minimum: 0
    maximum: 1
    format: double
  unrecoverableAmount:
    required: false
    displayName: UnrecoverableAmount
    description: The amount of input or import tax that the taxpayer is not able to recover. It is lost, which is a true cost to the taxpayer.
    type: number
    format: double
  filingCurrencyAmounts:
    required: false
    displayName: FilingCurrencyAmounts
    description: A grouping of filing currency converted taxability amounts.
    type: FilingCurrencyAmounts
  sellerRegistrationId:
    required: false
    displayName: SellerRegistrationId
    description: The Registration ID for the Seller associated with this line item tax.
    type: string
    minLength: 0
    maxLength: 40
  buyerRegistrationId:
    required: false
    displayName: BuyerRegistrationId
    description: The Registration ID for the Buyer associated with this line item tax.
    type: string
    minLength: 0
    maxLength: 40
  ownerRegistrationId:
    required: false
    displayName: OwnerRegistrationId
    description: The Registration ID for the Owner associated with this line item tax.
    type: string
    minLength: 0
    maxLength: 40
  dispatcherRegistrationId:
    required: false
    displayName: DispatcherRegistrationId
    description: The Registration ID for the Dispatcher associated with this line item tax.
    type: string
    minLength: 0
    maxLength: 40
  recipientRegistrationId:
    required: false
    displayName: RecipientRegistrationId
    description: The Registration ID for the Recipient associated with this line item tax.
    type: string
    minLength: 0
    maxLength: 40
  invoiceTextCode:
    required: false
    displayName: InvoiceTextCode
    description: |
        Indicator that alerts the host system of the need to add invoice text of a specific type to a line item. For a list of the codes and their meanings, see the Supporting Information section inthe XML Integration Guide.
        
        Note: This transaction is considered to involve a VAT group if a value of 2 (Intra-EU Notice) is returned, the POS jurisdiction is an EU country, and the buyer and seller have the same registration number.

    type: array
    items:
      type: integer
      format: int32
  summaryInvoiceText:
    required: false
    displayName: SummaryInvoiceText
    description: |
      Additional information about a tax, to be returned to your host system after tax calculation. To supply a value for this field, you need to set up a post-calculation Tax Assist rule.
      
      Note: The text you add to this field is not stored in the Tax Journal.
    type: string
  invoiceTexts:
    required: false
    displayName: InvoiceTexts
    type: array
    items:
      properties:
        invoiceTextCode:
          required: true
          displayName: InvoiceTextCode
          type: string
          description: The invoice text code.
        invoiceTextRuleId:
          required: true
          displayName: InvoiceTextRuleId
          type: integer
          description: The invoice text rule Id.
          minimum: 0
          maximum: 999999999
        userDefined:
          required: false
          displayName: UserDefined
          type: boolean
          description: An identifier for user-defined invoice text rule.
        text:
          required: false
          displayName: Text
          type: string
          description: The invoice text.
  assistedParameters:
    required: false
    displayName: AssistedParameters
    type: AssistedParameter[]
  taxRuleCurrencyConversionFactors:
    required: false
    displayName: TaxRuleCurrencyConversionFactors
    description: A list of tax rule currency conversion factors.
    type: array
    items:
      properties:
       taxRuleId:
        required: true
        displayName: TaxRuleId
        description: The tax rule that is applied during tax calculation
        type: Rule
       currencyConversionFactors:
        required: true
        displayName: CurrencyConversionFactors
        description: A list of currency conversion factors.
        type: CurrencyConversionFactor[]
  originalTax:
    required: false
    displayName: OriginalTax
    description: The tax amount before applying a tax credit rule.
    type: number
    format: double
  includedTax:
    required: false
    displayName: IncludedTax
    description: The total tax amount included in the basis.
    type: number
    format: double
  nominalRate:
    required: false
    displayName: NominalRate
    description: The original ICMS tax rate for origin and destination states.
    type: number
    format: double
  markUpRate:
    required: false
    displayName: MarkUpRate
    description: The Mark up rate.
    type: number
    format: double
  accumulateAsLineType:
    required: false
    displayName: AccumulateAsLineType
    description: Accumulate as Line Type of a telecom line.
    type: object
    properties:
      lineType:
        required: false
        displayName: LineType
        type: string
        description: Accumulate as Line Type of a telecom line.
      userDefined:
        required: false
        displayName: UserDefined
        type: boolean
        description: A flag to indicate the accumulate as line type is defined by user. 