#%RAML 1.0 NamedExample
value:
  systemId: 29313791
  isOnTest: true
  testTypeCode: "F"
  sequenceId: 9
  effectiveDate: "2015-02-25T18:35:00-05:00"
  expirationDate: "2015-02-25T19:35:00-05:00"
  testCategoryCode: "1"
  message: OK
  lastModifiedEmployeeId: 90030